apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ecommerce
  name: ecomm
spec:
  replicas: 20
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: cont1
        image: iamtejas23/e-commerce:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: abc
spec:
  type: LoadBalancer
  selector:
    app: ecommerce
  ports:
    - port: 80
      targetPort: 3000